name: Auto-merge Codex PRs

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: ${{ github.event.pull_request.user.login == 'codex[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: squash
      - name: Merge immediately if possible
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                merge_method: 'squash'
              });
              core.notice('Pull request merged.');
            } catch (error) {
              core.info('Merge not completed; checks or reviews may be required. Auto-merge will handle it later.');
            }
